%MACRO M_ETL_GENERATE_DATE;
	%GLOBAL
		mvDATETIME
	;
	%LET mvDATETIME=%SYSFUNC(COMPRESS(%SYSFUNC(TRANWRD(%SYSFUNC(PUTN(%SYSFUNC(TODAY()), YYMMDDN.))_%SYSFUNC(PUTN(%SYSFUNC(TIME()), TIME5.)), %STR(:), %STR(_)))));
%MEND M_ETL_GENERATE_DATE;