%MACRO M_ETL_OPEN_RESOURCE(mvRESOURCE);

	%LET mvRESOURCE=%sysfunc(upcase(&mvRESOURCE.));
	
	DATA _NULL_;
		mvRESOURCE="&mvRESOURCE.";
		CALL SYMPUT ("mvRESOURCE", STRIP(mvRESOURCE));
	RUN;
	
	PROC SQL NOPRINT;
		CREATE TABLE DATA_TO_APPEND AS
		SELECT
			RESOURCE_ID,
			RESOURCE_NM,
			"A" AS STATUS_CD,
			DHMS(today(), 00, 00, 00) AS PROCESSED_DTTM,
			. as BATCH_CYCLE_ID
		FROM
			etl_cfg.cfg_resource
		WHERE
			UPCASE(STRIP(RESOURCE_NM))=UPCASE(STRIP("&mvRESOURCE."))
		;
	QUIT;
	
	%M_ETL_APPEND_DATA(DATA_TO_APPEND, etl_cfg.cfg_status_table);
	/*
	PROC SQL NOPRINT;
		CONNECT TO POSTGRES AS CONN (server="10.252.151.3" port=5452 user=etl_cfg password="{SAS002}1D57933958C580064BD3DCA81A33DFB2" database=etl defer=yes readbuff=32767 conopts="UseServerSidePrepare=1;UseDeclareFetch=1;Fetch=8192");
		EXECUTE BY CONN
			(
				UPDATE ETL_CFG.CFG_STATUS_TABLE
				SET BATCH_CYCLE_ID=
					(
						SELECT MAX(BATCH_ID) FROM ETL_CFG.CFG_BATCH_ETL_CYCLE
					)
				WHERE
					RESOURCE_NM=%STR(%')&mvRESOURCE.%STR(%') AND
					STATUS_CD='A'
			)
		;
		DISCONNECT FROM CONN;
	QUIT;
	*/
%MEND M_ETL_OPEN_RESOURCE;